### ISSUE TITLE
Jump to source for functions

### ISSUE THREAD

**Issue by wilzbach** [adamdruppe/adrdox#13]
The power of D is that the source code is very easy to read, so it would be nice if I could jump to the source code directly from a method page.

Most files are pretty big and Ctrl-F works well, but is annonying ;-)

**Comment by adamdruppe** [comment]
I actually added this like a year ago, and this last weekend, added jumping from inside the source page too.

Check it out. You're on the simpledisplay timer:
http://dpldocs.info/experimental-docs/arsd.simpledisplay.Timer.this.html

You hit see implementation and it jumps to the file. Scroll down a bit and you see a call to function prepareEventLoop
http://dpldocs.info/experimental-docs/source/arsd.simpledisplay.d.html#L3591

and you can click it to go right back to the definition! I'll be rebuilding the Phobos files soon to include that feature too (currently the generator supports it but i have only generated sdpy since then).
