### ISSUE TITLE
Mention the version of the generated docs

### ISSUE THREAD

**Issue by wilzbach** [adamdruppe/adrdox#20]
It would be great to know which version of the library was used to generate the docs.
This is especially interesting for "fast-moving" libs like Vibe.d, Mir and even Phobos.

**Comment by adamdruppe** [comment]
Yeah, in fact, I think I might generate specific versions on demand and put them in subdirectories (I should have done that before releasing anything, but meh).

I'm up to 115 MB right now from what people have already generated, some 30 projects. But with the on-demand thing, I could always delete less-frequently requested stuff if needed... I just gotta spend a little more time on the scraper.

**Comment by adamdruppe** [comment]
so yeah i can get the zip for any version right off github so basically the same code can do this...

Well, it took me a lot longer than I thought to write this but I cleaned up some of my code in the process. Behold:

http://dpq.dpldocs.info/v0.9.3/dpq.attributes.html

a specific version in the url or

http://dpq.dpldocs.info/dpq.html

which just pulled the ~master branch.

I deleted all teh stuff from earlier today so it can regenerate. I kinda wanna change the page header a bit too, maybe even allow projects to customize it slightly with a config file in the repo... but I'll come back to that later, it is WAY past bed time.

**Comment by wilzbach** [comment]
Wow that's really cool. Thanks!

> which just pulled the ~master branch.

Hmm that could easily go out of date.
Do you plan on pulling this daily?

**Comment by adamdruppe** [comment]
I haven't decided yet. I don't want it to be automatically pulling very often because the generator is actually pretty resource-intensive and can bring the server down for a minute while it works on some projects (i could prolly fork over a bit more money and put it on a separate work server if it becomes a big problem but for now i wanna keep the cost as low as i can) 

So it might recheck periodically and treat master like an expiring cache... but I don't want to just cron job anything because I like it being able to just build on demand. Well, I might cron job archiving stuff that hasn't been accessed recently if disk space becomes an issue. But I like it being on-demand.

I might also just have a "force refresh" thing. idk yet.

**Comment by adamdruppe** [comment]
So I put the date in the header:
http://arsd-official.dpldocs.info/arsd.dom.html

or for a particular version:
http://dplug.dpldocs.info/v6.0.22/dplug.core.fpcontrol.html

The date is the commit date (pulled from dub api) so you can get an idea of how old the code is. I might move it from the header, but I do love having the date around for basically everything.

**Comment by wilzbach** [comment]
Thanks!
