### ISSUE TITLE
Many missing modules

### ISSUE THREAD

**Issue by andrewbenton** [adamdruppe/adrdox#24]
The auto-generated documentation for my [project](https://prometheus.dpldocs.info/prometheus.html) is missing most of the modules and classes.  It's only showing the `prometheus.metric` module and `Metric` class, even though there are seven modules located under the top level `prometheus` with classes.

Project source [here](https://github.com/andrewbenton/prometheus-d).

**Comment by adamdruppe** [comment]
On Mon, May 28, 2018 at 11:28:19PM -0700, Andrew Benton wrote:
> Project source [here](https://github.com/andrewbenton/prometheus-d).

There's almost zero documentation comments in there. Items without doc comments are skipped i doc generation.

Minimally, you can add an empty

///

to the things you want to show up.

**Comment by andrewbenton** [comment]
Oh, good to know.  I figured it would always pull out the method / class signatures.  Thanks!

**Comment by adamdruppe** [comment]
On Thu, May 31, 2018 at 11:48:04AM -0700, Andrew Benton wrote:
> Oh, good to know.  I figured it would always pull out the method / class signatures.  Thanks!

I might make that an option eventually but the idea there is I sometimes
like to have public but undocumented functions which are like "you can try this but no guarantee".

Whereas once something appears in the docs formally, I feel obligated to support it. That's why I kept that opt in with ///. And since ddoc does the same, I'm ok with that.

There is a slight exception though: plain data struct members can show in the summary even when undocumented. I think.
