### ISSUE TITLE
Please add the dub package version to the generated docs if possible

### ISSUE THREAD

**Issue by gizmomogwai** [adamdruppe/adrdox#33]
This would help to see, if the docs match the dub package version actually used.

**Comment by adamdruppe** [comment]
That's not available to the generator alone, but the web version does, it can actually generate for any version and will tell you in the header. For example

http://arsd-official.dpldocs.info/v4.3.2/arsd.cgi.html

that's for version 4.3.2 as you can see in the url, an the page header says "2019-12-07T04:23:59Z" which is when that version was git committed.

or the master version

http://arsd-official.dpldocs.info/master/arsd.cgi.html

(2020-02-22T01:06:07Z)

which shows when that page was last regenerated.

when running the generator locally, you need to pass the header via command line arg because the generator itself only looks at files, it doesn't know about versions.

**Comment by gizmomogwai** [comment]
thanks a lot!
