### ISSUE TITLE
CI failed, dpldocs.info down

### ISSUE THREAD

**Issue by veelo** [adamdruppe/adrdox#56]
Hi Adam,

I hope you are doing well. You may already be aware that http://dpldocs.info/experimental-docs/adrdox.syntax.html is down. Could that be due to the adrdox CI failure? It seems that the github internal server error that caused this failure has been resolved, so maybe it is just a matter of restarting the CI.

Best,
Bastiaan.

**Comment by adamdruppe** [comment]
No, it was because a big storm knocked to power to my city all day, once the power came back on the server restarted and we're all set.

The dpldocs.info subdomains are hosted on another server btw in a different location so if this kind of thing happens you can still go to yourproject.dpldocs.info but hard to say that when everything here is dead lol

**Comment by veelo** [comment]
Thanks, cheers.
